title: Ruixi Zhong's Homepage
page-top-title: Ruixi Zhong
top-section-bg-text: Hunan University
top-section-subtitle: --Computer Science Department 
home-subtitle:  Ruixi Zhong&ensp;|&ensp;钟睿熙
copyright-text: '&copy;  Ruixi Zhong 2024-2025. All Rights Reserved.'
publications-subtitle: RESEARCH EXPERIENCES
awards-subtitle: AWARDS&CERTIFICATIONS