title: Ruixi Zhong's Homepage
page-top-title: Ruixi Zhong
top-section-bg-text: Hunan University--Computer Science
home-subtitle:  Ruixi Zhong&ensp;|&ensp;钟睿熙
copyright-text: '&copy;  Ruixi Zhong 2024-2025. All Rights Reserved.'
