title: Ruixi Zhong's Homepage
page-top-title: Ruixi Zhong
top-section-bg-text: Computer Science
home-subtitle:  Ruixi Zhong&ensp;|&ensp;钟睿熙
copyright-text: '&copy;  Ruixi Zhong 2023-2024. All Rights Reserved.'
